AllCops:
  Exclude:
    - Gemfile
    - 'bin/**/*'
    - 'config/**/*'
    - config.ru
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - app/helpers/application_helper.rb

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
